clear all;clc;close all;
%% data points
x2 = [1.159,1.601,1.693,0.4127,0.9846,0.5608,2.929,0.5614,2.296];
y2 = [0.8187,4.969,4.437,3.948,1.244,4.968,1.018,2.667,3.645];
z2 = [6.486,63.05,51.88,34.21,7.592,54.03,13.29,17.03,40.84];

% T = table(transpose(x2),transpose(y2),transpose(z2));
% figure;
% plot3(x2,y2,z2,'ko','linewidth',2, 'markerfacecolor', 'k');
% grid on;
% xlabel('X')
% ylabel('Y')
% zlabel('Z')

%% plot using meshgrid
[xx,yy] = meshgrid(0:0.05:5);
zz = griddata(x2,y2,z2,xx,yy,'cubic');

figure;
mesh(xx,yy,zz);
hold on;
plot3(x2,y2,z2,'bo','linewidth',2,'markerfacecolor','b');
grid on;
hold off;
xlabel('X')
ylabel('Y')
zlabel('Z')
legend('Piecewise Cubic Surface');
print -depsc epsFig;
%% cubic fit
%CREATEFIT(X2,Y2,Z2)
%  Create a fit.
%
%  Data for '2_cubicfit' fit:
%      X Input : x2
%      Y Input : y2
%      Z Output: z2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-May-2020 20:36:44


%% Fit: '2_cubicfit'.
[xData, yData, zData] = prepareSurfaceData( x2, y2, z2 );

% Set up fittype and options.
ft = 'cubicinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', '2_cubicfit' );
h = plot( fitresult, [xData, yData], zData );
legend( h, '2_cubicfit', 'z2 vs. x2, y2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x2', 'Interpreter', 'none' );
ylabel( 'y2', 'Interpreter', 'none' );
zlabel( 'z2', 'Interpreter', 'none' );
grid on
view( -47.8, 13.5 );

%% Fit: '2_polyfit'.
[xData, yData, zData] = prepareSurfaceData( x2, y2, z2 );

% Set up fittype and options.
ft = fittype( 'poly12' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', '2 Polynomial Fit' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Polynomial fit', 'z2 vs. x2, y2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'X', 'Interpreter', 'none' );
ylabel( 'Y', 'Interpreter', 'none' );
zlabel( 'Z', 'Interpreter', 'none' );
grid on
view( -63.6, 37.0 );

figure
plot(x2,z2,'ro','linewidth',2);
grid on
hold on
plot(x2,2.903 + 2.201.*x2 + -1.924.*y2 + 1.153.*x2.*y2 + 2.295.*y2.^2,'kx','linewidth',2);
hold off
legend('Data Points x, z', 'Polynomial Fit x, z');

figure
plot(y2,z2,'ro','linewidth',2);
grid on
hold on
plot(y2,2.903 + 2.201.*x2 + -1.924.*y2 + 1.153.*x2.*y2 + 2.295.*y2.^2,'kx','linewidth',2);
hold off
legend('Data Points y, z', 'Polynomial Fit y, z');

z_error = zeros(1,9);
for i=1:9
    z_error(i) = abs(z2(i) - (2.903 + 2.201.*x2(i) + -1.924.*y2(i) + 1.153.*x2(i).*y2(i) + 2.295.*y2(i).^2)).^2;
end 

%% Test Data
% Plot fit with data.
figure( 'Name', '2 Polynomial Fit' );
h = plot( fitresult, [xData, yData], zData );
hold on

% Label axes
xlabel( 'X', 'Interpreter', 'none' );
ylabel( 'Y', 'Interpreter', 'none' );
zlabel( 'Z', 'Interpreter', 'none' );
grid on
view( -63.6, 37.0 );

test_x2 = [4.063,0.8043,2.339,4.976,1.926,3.602];
test_y2 = [3.14,4.268,4.27,2.809,2.946,4.621];
test_z2 = [45.57,43.21,53.93,44.34,29.72,70.19];
plot3(test_x2,test_y2,test_z2, 'ro', 'markerfacecolor', 'r');
legend('Train Data', 'Test Data', 'Location', 'NorthEast');
print -depsc epsFig;

error = 0;
for i=1:6
    error = error + (test_z2(i)-(2.903 + 2.201.*test_x2(i) + -1.924.*test_y2(i) + 1.153.*test_x2(i).*test_y2(i) + 2.295.*test_y2(i).^2)).^2;
end
error = error / 6;